name: cd

on:
  push:
    branches: ["main"]


jobs:
  ci:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: yukberhemat
          POSTGRES_DB: heymattest
          POSTGRES_USER: heymat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: run test
        run: go test -v

      - name: build binary
        run: GOOS=linux GOARCH=amd64 go build -v -o heymat .

      - name: copy built binary
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          source: "heymat"
          target: "~/bin"

      - name: restart service
        uses: appleboy/ssh-action/@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          script: |
            systemctl daemon-reload
            systemctl restart heymat
