name: cd

on:
  push:
    branches: ["main"]


jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: yukberhemat
          POSTGRES_DB: heymattest
          POSTGRES_USER: heymat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: run test
        run: go test -v
